{% set name = "weldx_widgets" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0daec839e34802c6db95ae2944163ae12823a0df315e81aa1c9170c77999769
build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
        - babel
      run:
        - python >={{ python_min }}
        - weldx >=0.6.9
        - ipywidgets >=8.1
        - k3d <2.17
        - ipympl
        - bidict
        - ipyfilechooser
        - tqdm
        - matplotlib-base >=3.8
        - numpy
        - pint

    test:
      imports:
        - weldx_widgets
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
  # alias
  - name: weldx-widgets
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - weldx_widgets

about:
  home: https://github.com/BAMWeldX/weldx-widgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Visualization frontends for the open science weldx data format.'
  description: |
    weldx widgets provide plotting routines for commonly used data structures
    in weldx. Further it contains widgets to create forms for designing welding
    experiments, and analyze data.
  doc_url: https://github.com/BAMWeldX/weldx-widgets
  dev_url: https://github.com/BAMWeldX/weldx-widgets

extra:
  recipe-maintainers:
    - CagtayFabry
