{% set name = "weldx_widgets" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76d29d780451c46cdd951b10fb83d00392b7362f47b60df7b9c94a33aa462a58
build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.9
        - pip
        - setuptools
        - setuptools_scm
        - babel
      run:
        - python >=3.8,<3.12
        - weldx >=0.6
        - ipywidgets
        - k3d
        - ipympl
        - bidict
        - ipyfilechooser
        - tqdm
        - matplotlib <3.9
        - numpy <2

    test:
      imports:
        - weldx_widgets
      requires:
        - pip
      commands:
        - pip check
  # alias
  - name: weldx-widgets
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - weldx_widgets

about:
  home: https://github.com/BAMWeldX/weldx-widgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Visualization frontends for the open science weldx data format.'
  description: |
    weldx widgets provide plotting routines for commonly used data structures
    in weldx. Further it contains widgets to create forms for designing welding
    experiments, and analyze data.
  doc_url: https://github.com/BAMWeldX/weldx-widgets
  dev_url: https://github.com/BAMWeldX/weldx-widgets

extra:
  recipe-maintainers:
    - marscher
    - CagtayFabry
